### ISSUE TITLE
Symmetric difference?

### ISSUE THREAD

**Issue by CoDEmanX** [Turfjs/turf-difference#10]
Aside from union, intersection and difference, there is a 4th geometric operation: symmetric difference. It is available in JSTS as geom.symDifference(). Any plans to add it to turf?

**Comment by morganherlocker** [comment]
This issue outlines the operations we would like to support in the future https://github.com/Turfjs/turf/issues/203

**Comment by CoDEmanX** [comment]
As a workaround, this should work too:

    (B diff A) union (A diff B)

or

    (A union B) diff (A intersect B)
