### ISSUE TITLE
Remove "difference" layer between two Geojson layers using Turfjs

### ISSUE THREAD

**Issue by marie15** [Turfjs/turf-difference#15]
I've draw line programmatically (not using leaflet draw) inside polygone using leaflet draw plugin on map, I want to keep only the points of polyline that are inside of polygone and remove those are outside. Using **difference** method of **Turfsjs** library, I can get the "difference" layer between the polygon and line, now I want to remove this "difference" layer from map and keep only the polygone and part of line that is inside the polygon. Any help is much appreciated. Thank you.
Here is a code snippet:

`var line = path.toGeoJSON();
var polygon = selectedPoly.toGeoJSON();
var difference, result = [];
difference = turf.difference(line, polygon);
if (difference) 
{
    result.push(difference);
    var inter = L.geoJson(result).addTo(map);
}`

**Comment by DenisCarriere** [comment]
Are you using the latest `@turf/difference`?
https://github.com/Turfjs/turf/tree/master/packages/turf-difference

Could you please re-submit your issue on the main Turf repo and follow any instructions given while submitting an issue.
https://github.com/Turfjs/turf/issues

**Comment by marie15** [comment]
I didn't use @turf/difference, I add this script to my page <script src="https://npmcdn.com/@turf/turf@3.5.1/turf.js"></script>, Is it a bad approch? . Ok thank you @DenisCarriere, I will move this post to the convinenent repo
