### ISSUE TITLE
Rename to turf-difference

### ISSUE THREAD

**Issue by tchannel** [Turfjs/turf-difference#6]
Per discussion in Turfjs/turf#137

Keep the alias to turf-erase in the main turf build for compatibility

**Comment by morganherlocker** [comment]
I'm totally on board with this. I think we should even go a step further and not keep the alias. This can be a major turf version bump, since it will be a breaking api change.

**Comment by tchannel** [comment]
- [ ] Rename github repo
- [ ] Rename package.json
- [ ] Republish on npm
- [ ] Update dep in Turfjs/turf
- [ ] Tag 3.0.0
- [ ] Update any docs / examples using erase
- [ ] Update cdn links on turfjs.org

**Comment by morganherlocker** [comment]
https://github.com/Turfjs/turf-difference/releases/tag/v2.0.0

^ This is done. The release will be rolled into a Turf major version.
